# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
        ('users', '0004_auto_20180801_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cunauser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='cunauser',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='cunauser',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='cunauser',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='cunauser',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cunauser',
            name='miembro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.Miembro'),
        ),
        migrations.AlterField(
            model_name='cunauser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
    ]
