# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.Banco'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
