# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_auto_20180804_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='cuenta',
            field=models.CharField(blank=True, default='.', max_length=50),
            preserve_default=False,
        ),
    ]
